# version: "3.8"

# services:
#   broker-service:
#     build:
#       context: /home/louis/Desktop/go-micro/broker-service
#       dockerfile: cmd/api/broker-service.dockerfile
#     restart: always
#     ports:
#       - "8084:8083"
#     # Removed deploy section as it's not supported in non-Swarm mode

#   authentication-service:
#     build:
#       context: ./../authentication-service
#       dockerfile: ./../authentication-service/authentication-service.dockerfile
#     restart: always
#     ports:
#       - "8081:80" # Fixed indentation
#     environment:
#       DSN: "host=postgres port=5434 user=postgres password=password dbname=user sslmode=disable timezone=UTC connect_timeout=5"
#     # Removed delay and deploy sections, as these aren't appropriate for standard docker-compose deployments

#   postgres:
#     image: "postgres:14.0"
#     ports:
#       - "5434:5432"
#     restart: always
#     environment:
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#       POSTGRES_DB: users
#     volumes:
#       - ./db-data/postgres:/var/lib/postgresql/data # Fixed volume mapping

version: '3.8'

services:

  broker-service:
    build:
      context: ../broker-service
      dockerfile: cmd/api/broker-service.dockerfile
    restart: always
    ports:
      - "8084:8083"
    deploy:
      mode: replicated
      replicas: 1

  authentication-service:
    build:
      context: ./../authentication-service
      dockerfile: ./../authentication-service/authentication-service.dockerfile
    restart: always
    ports:
      - "9003:8084"
    deploy:
      mode: replicated
      replicas: 1
    environment:
      DSN: "host=postgres port=5432 user=postgres password=password dbname=users sslmode=disable timezone=UTC connect_timeout=5"


  postgres:
    image: 'postgres:14.0'
    ports:
      - "5434:5432"
    restart: always
    deploy:
      mode: replicated
      replicas: 1
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: users
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/